services:
  polled-web:
    container_name: polled
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID: ${EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID}
        EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID: ${EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID}
        EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID: ${EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID}
        EXPO_PUBLIC_ANALYTICS_INGEST_URL: ${EXPO_PUBLIC_ANALYTICS_INGEST_URL}
    #ports:
    #  - "8080:80"
    restart: unless-stopped
    
networks:
  default:
    external: true
    name: serverout
